name: shoppy
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  alphabet_list_scroll_view: ^2.0.0
  backdrop: ^0.6.1
  badges: ^2.0.1
  cached_network_image: ^3.0.0
  carousel_pro: ^1.0.0
  cloud_firestore: ^2.2.0
  cupertino_icons: ^1.0.2
  faker: ^2.0.0
  firebase_auth: ^1.1.4
  firebase_core: ^1.1.1
  firebase_storage: ^8.1.0
  flutter_absolute_path: ^1.0.6
  flutter_icons: ^1.1.0
  flutter_image_compress: ^1.0.0
  flutter_staggered_grid_view: ^0.4.0
  flutter_swiper: ^1.1.6
  google_sign_in: ^5.0.3
  image_picker: ^0.7.5+3
  list_tile_switch: ^1.0.0
  multi_image_picker: ^4.8.0
  provider: ^5.0.0
  shared_preferences: ^2.0.5
  transparent_image: ^2.0.0
  wave: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
